/**
 * AUTOGENERATED FILE — DO NOT EDIT DIRECTLY.
 *
 * Generated by backend scripts/generate-native-festival-content.mts from
 * packages/dharma-rules/src/festivals/festival-content.json.
 *
 * Sourced canonical editorial content for single-day festival detail pages.
 * Reuses the same editorial-gating vocabulary (LocalizedEditorialField /
 * EditorialStatus) already established for multi-day observance series —
 * see lib/observance-series-contract.generated.ts.
 */

import type { LocalizedEditorialField } from './observance-series-contract.generated';

export interface FestivalMantraContent {
  sanskrit: string;
  transliteration: string;
  translation: LocalizedEditorialField<{ en: string; hi?: string; pa?: string }>;
}

export interface FestivalContent {
  definitionKey: string;
  emoji: string;
  tradition: string;
  name: LocalizedEditorialField<{ en: string; hi?: string; pa?: string }>;
  tagline: LocalizedEditorialField<{ en: string; hi?: string; pa?: string }>;
  significance: LocalizedEditorialField<{ en: string; hi?: string; pa?: string }>;
  rituals: LocalizedEditorialField<{ en: string[]; hi?: string[]; pa?: string[] }>;
  dos?: LocalizedEditorialField<{ en: string[]; hi?: string[]; pa?: string[] }>;
  donts?: LocalizedEditorialField<{ en: string[]; hi?: string[]; pa?: string[] }>;
  pujaItems?: LocalizedEditorialField<{ en: string[]; hi?: string[]; pa?: string[] }>;
  mantra?: FestivalMantraContent;
}

export interface FestivalContentSnapshot {
  version: string;
  festivals: FestivalContent[];
}

export const FESTIVAL_CONTENT_SNAPSHOT: FestivalContentSnapshot = {
  "version": "1.0.0",
  "festivals": [
    {
      "definitionKey": "raksha-bandhan",
      "emoji": "🧵",
      "tradition": "hindu",
      "name": {
        "value": {
          "en": "Raksha Bandhan"
        },
        "status": "council_reviewed_editorial",
        "reviewRef": "owner-approval-2026-08-26",
        "sourceRefs": [],
        "applicability": {
          "universal": true
        }
      },
      "tagline": {
        "value": {
          "en": "A sacred thread of protection between siblings"
        },
        "status": "council_reviewed_editorial",
        "reviewRef": "owner-approval-2026-08-26",
        "sourceRefs": [],
        "applicability": {
          "universal": true
        }
      },
      "significance": {
        "value": {
          "en": "Raksha Bandhan celebrates the bond between brothers and sisters. A sister ties a protective thread (rakhi) on her brother's wrist as a symbol of her love and prayers for his wellbeing, and he in turn pledges to protect and support her. The festival is observed on the full moon (Purnima) of the lunar month of Shravana."
        },
        "status": "council_reviewed_editorial",
        "reviewRef": "owner-approval-2026-08-26",
        "sourceRefs": [
          {
            "sourceName": "Widely cited traditional festival account — editorially approved; exact primary-text citation still unverified",
            "tier": 3,
            "usagePermitted": "internal_review_only"
          }
        ],
        "applicability": {
          "universal": true
        }
      },
      "rituals": {
        "value": {
          "en": [
            "Sister performs a short aarti and applies tilak on her brother's forehead",
            "Sister ties the rakhi thread on her brother's right wrist",
            "Brother offers a gift and pledges to protect and support his sister",
            "Sweets are exchanged between siblings"
          ]
        },
        "status": "council_reviewed_editorial",
        "reviewRef": "owner-approval-2026-08-26",
        "sourceRefs": [
          {
            "sourceName": "Widely cited traditional practice — editorially approved; exact primary-text citation still unverified",
            "tier": 3,
            "usagePermitted": "internal_review_only"
          }
        ],
        "applicability": {
          "universal": true
        }
      },
      "dos": {
        "value": {
          "en": [
            "Tie the rakhi during an auspicious muhurat when possible",
            "Sit facing east or north during the ritual"
          ]
        },
        "status": "council_reviewed_editorial",
        "reviewRef": "owner-approval-2026-08-26",
        "sourceRefs": [
          {
            "sourceName": "Widely cited traditional practice — editorially approved; exact primary-text citation still unverified",
            "tier": 3,
            "usagePermitted": "internal_review_only"
          }
        ],
        "applicability": {
          "universal": true
        }
      },
      "donts": {
        "value": {
          "en": [
            "Avoid tying the rakhi during Bhadra kaal, considered inauspicious"
          ]
        },
        "status": "council_reviewed_editorial",
        "reviewRef": "owner-approval-2026-08-26",
        "sourceRefs": [
          {
            "sourceName": "Widely cited traditional practice — editorially approved; exact primary-text citation still unverified",
            "tier": 3,
            "usagePermitted": "internal_review_only"
          }
        ],
        "applicability": {
          "universal": true
        }
      },
      "pujaItems": {
        "value": {
          "en": [
            "Rakhi thread",
            "Roli/kumkum",
            "Rice grains",
            "Diya",
            "Sweets"
          ]
        },
        "status": "council_reviewed_editorial",
        "reviewRef": "owner-approval-2026-08-26",
        "sourceRefs": [],
        "applicability": {
          "universal": true
        }
      },
      "mantra": {
        "sanskrit": "येन बद्धो बली राजा दानवेन्द्रो महाबलः। तेन त्वामनुबध्नामि रक्षे मा चल मा चल॥",
        "transliteration": "yena baddho balī rājā dānavendro mahābalaḥ, tena tvām anubadhnāmi rakṣe mā cala mā cala",
        "translation": {
          "value": {
            "en": "With the same thread that bound the mighty king of demons [Bali], I bind you, O protective thread — may you not falter, may you not falter."
          },
          "status": "council_reviewed_editorial",
          "reviewRef": "owner-approval-2026-08-26",
          "sourceRefs": [
            {
              "sourceName": "Commonly attributed to the Bhavishya Purana in popular tradition — editorially approved; exact verse location still unverified",
              "tier": 3,
              "usagePermitted": "internal_review_only"
            }
          ],
          "applicability": {
            "universal": true
          }
        }
      }
    }
  ]
} as const;

export const FESTIVAL_CONTENT_BY_SLUG: Record<string, FestivalContent> = Object.fromEntries(
  FESTIVAL_CONTENT_SNAPSHOT.festivals.map(f => [f.definitionKey, f])
);

export function lookupFestivalContent(slug: string): FestivalContent | null {
  return FESTIVAL_CONTENT_BY_SLUG[slug] ?? null;
}
