/**
 * observance-series-content.ts
 *
 * Client-side helper for accessing sourced multi-day observance series content.
 * Consumes the versioned autogenerated snapshot (observance-series-content.generated.ts).
 */

import {
  OBSERVANCE_SERIES_CONTENT_SNAPSHOT,
  OBSERVANCE_SERIES_CHILD_CONTENT_BY_SLUG,
  type SourcedSeriesChildContent,
  type SourcedSeriesGroupContent,
  type LocalizedEditorialField,
} from './observance-series-content.generated';

export type SupportedLanguage = 'en' | 'hi' | 'pa';

export interface EditorialApplicabilityContext {
  region?: string;
  calendarProfile?: string;
  tradition?: string;
  sampradaya?: string;
}

function includesNormalized(values: string[] | undefined, candidate: string | undefined): boolean {
  if (!values?.length) return true;
  if (!candidate) return false;
  const normalizedCandidate = candidate.trim().toLocaleLowerCase();
  return values.some(value => value.trim().toLocaleLowerCase() === normalizedCandidate);
}

export function isEditorialFieldDisplayable<T>(
  field: LocalizedEditorialField<T> | null | undefined,
  context?: EditorialApplicabilityContext,
): field is LocalizedEditorialField<T> {
  if (!field) return false;
  if (field.status === 'pending_source' || field.status === 'withheld') return false;
  if (field.status === 'source_backed' && field.sourceRefs.length === 0) return false;
  if (field.status === 'council_reviewed_editorial' && !field.reviewRef) return false;

  const applicability = field.applicability;
  const hasScopedValues = Boolean(
    applicability.regions?.length
    || applicability.calendarProfiles?.length
    || applicability.traditions?.length
    || applicability.sampradayas?.length,
  );
  if (applicability.universal) return !hasScopedValues;

  return hasScopedValues
    && includesNormalized(applicability.regions, context?.region)
    && includesNormalized(applicability.calendarProfiles, context?.calendarProfile)
    && includesNormalized(applicability.traditions, context?.tradition)
    && includesNormalized(applicability.sampradayas, context?.sampradaya);
}

/**
 * Retrieves the editorial content definition for a specific child observance by slug.
 */
export function getSeriesChildContent(slug: string): SourcedSeriesChildContent | undefined {
  return OBSERVANCE_SERIES_CHILD_CONTENT_BY_SLUG[slug];
}

/**
 * Retrieves all children for a series group by definitionKey (e.g. 'sharad-navratri', 'diwali-five-days').
 */
export function getSeriesGroupContent(definitionKey: string): SourcedSeriesGroupContent | undefined {
  return OBSERVANCE_SERIES_CONTENT_SNAPSHOT.series.find(s => s.definitionKey === definitionKey);
}

/**
 * Resolves a localised string from a LocalizedEditorialField or raw localized object with fallback to English.
 */
export function resolveLocalizedText(
  field?: LocalizedEditorialField<{ en: string; hi?: string; pa?: string }> | { en: string; hi?: string; pa?: string } | null,
  lang: SupportedLanguage = 'en',
  context?: EditorialApplicabilityContext,
): string {
  if (!field) return '';
  if ('value' in field && !isEditorialFieldDisplayable(field, context)) return '';
  const obj = 'value' in field ? field.value : field;
  if (!obj) return '';
  const translationStatus = 'value' in field ? field.translationStatus : undefined;
  if (lang === 'hi' && obj.hi && translationStatus?.hi !== 'pending') return obj.hi;
  if (lang === 'pa' && obj.pa && translationStatus?.pa !== 'pending') return obj.pa;
  if (translationStatus?.en === 'pending') return '';
  return obj.en || '';
}

/**
 * Resolves a localised string array from a LocalizedEditorialField or raw localized list with fallback to English.
 */
export function resolveLocalizedList(
  field?: LocalizedEditorialField<{ en: string[]; hi?: string[]; pa?: string[] }> | { en: string[]; hi?: string[]; pa?: string[] } | null,
  lang: SupportedLanguage = 'en',
  context?: EditorialApplicabilityContext,
): string[] {
  if (!field) return [];
  if ('value' in field && !isEditorialFieldDisplayable(field, context)) return [];
  const obj = 'value' in field ? field.value : field;
  if (!obj) return [];
  const translationStatus = 'value' in field ? field.translationStatus : undefined;
  if (lang === 'hi' && obj.hi && obj.hi.length > 0 && translationStatus?.hi !== 'pending') return obj.hi;
  if (lang === 'pa' && obj.pa && obj.pa.length > 0 && translationStatus?.pa !== 'pending') return obj.pa;
  if (translationStatus?.en === 'pending') return [];
  return obj.en || [];
}

/**
 * Derives a clean, tradition-accurate, compact day label (e.g. 'Day 1 · Dhanteras' or 'दिन १ · शैलपुत्री')
 * for any multi-day series child observance across Sharad Navratri, Diwali, Chhath Puja, Ganeshotsav, etc.
 */
export function formatSeriesDayLabel(
  child: { sequence: number; canonicalTitle?: { value?: { en?: string; hi?: string; pa?: string } } },
  lang: SupportedLanguage = 'en',
): string {
  const isHi = lang === 'hi';
  const isPa = lang === 'pa';
  const rawTitle = (isHi ? child.canonicalTitle?.value?.hi : isPa ? child.canonicalTitle?.value?.pa : child.canonicalTitle?.value?.en)
    || child.canonicalTitle?.value?.en
    || '';

  let specific = '';
  if (rawTitle.includes('—')) {
    specific = rawTitle.split('—')[1].trim();
  } else if (rawTitle.includes('–')) {
    specific = rawTitle.split('–')[1].trim();
  } else {
    specific = rawTitle;
  }
  specific = specific.split('(')[0].split('/')[0].trim();

  if (rawTitle.toLowerCase().includes('visarjan') || rawTitle.includes('विसर्जन') || rawTitle.includes('ਵਿਸਰਜਨ')) {
    specific = isHi ? 'विसर्जन' : isPa ? 'ਵਿਸਰਜਨ' : 'Visarjan';
  } else if (specific.toLowerCase().includes('chaturthi') || specific.includes('चतुर्थी') || specific.includes('ਚੌਥ')) {
    specific = isHi ? 'गणेश चतुर्थी' : isPa ? 'ਗਣੇਸ਼ ਚੌਥ' : 'Chaturthi';
  } else if (specific.toLowerCase().includes('dussehra') || specific.toLowerCase().includes('vijayadashami') || specific.includes('दशहरा') || specific.includes('विजयादशमी')) {
    specific = isHi ? 'विजयादशमी' : isPa ? 'ਦੁਸਹਿਰਾ' : 'Dussehra';
  }
  if (specific.toLowerCase().includes('day ') || specific.includes('दिन ') || specific.includes('ਦਿਨ ')) {
    specific = '';
  }

  const dayPrefix = isHi ? `दिन ${child.sequence}` : isPa ? `ਦਿਨ ${child.sequence}` : `Day ${child.sequence}`;
  return specific ? `${dayPrefix} · ${specific}` : dayPrefix;
}
