/**
 * Panchatantra Expanded Content Provider
 * 
 * Provides versioned snapshot access to the 98 depth-expanded
 * Panchatantra stories (6 paragraphs English + 6 paragraphs Devanagari Hindi,
 * single emoji portrait).
 *
 * The snapshot is GENERATED by the backend (scripts/generate-native-panchatantra-expanded.mts)
 * from its canonical content and katha-library. Never edit it by hand, and never
 * synthesise a title or moral here: an unknown story renders nothing offline
 * rather than placeholder prose.
 */

import expandedSnapshot from '@/assets/data/panchatantra-expanded-snapshot.json';

export interface ExpandedPanchatantraEntry {
  id: string;
  title: string;
  titleHi: string;
  phal: string;
  phalHi: string;
  portrait: string;
  durationMin: number;
  body: string[];
  bodyHi: string[];
}

const EXPANDED_MAP = new Map<string, ExpandedPanchatantraEntry>();

(expandedSnapshot as ExpandedPanchatantraEntry[]).forEach((item) => {
  if (item && item.id) {
    EXPANDED_MAP.set(item.id, item);
  }
});

/**
 * Returns the expanded 6-paragraph entry for a given Panchatantra story ID, if available.
 */
export function getExpandedPanchatantraStory(id: string): ExpandedPanchatantraEntry | undefined {
  if (!id) return undefined;
  return EXPANDED_MAP.get(id.trim());
}

/**
 * Enhances a katha object with expanded 6-paragraph body, bodyHi, and portrait
 * if an expanded version exists in the versioned snapshot.
 */
export function enhanceWithExpandedPanchatantra<T extends { id: string; body: string[]; bodyHi?: string[]; portrait?: string; durationMin?: number }>(
  katha: T
): T {
  const expanded = getExpandedPanchatantraStory(katha.id);
  if (!expanded) return katha;

  return {
    ...katha,
    body: expanded.body.length > katha.body.length ? expanded.body : katha.body,
    bodyHi: expanded.bodyHi?.length ? expanded.bodyHi : katha.bodyHi,
    portrait: expanded.portrait || katha.portrait,
    durationMin: expanded.durationMin || katha.durationMin,
  };
}

/**
 * Creates an offline standalone FullKatha from the generated snapshot.
 * Title and moral are the canonical ones shipped in the snapshot; if either is
 * missing this returns null instead of inventing placeholder text.
 */
export function createOfflinePanchatantraKatha(id: string) {
  const expanded = getExpandedPanchatantraStory(id);
  if (!expanded?.title || !expanded.phal) return null;

  return {
    id: expanded.id,
    tradition: 'hindu',
    occasion: 'general',
    title: expanded.title,
    titleHi: expanded.titleHi,
    preview: expanded.body[0]?.slice(0, 150) ?? '',
    body: expanded.body,
    bodyHi: expanded.bodyHi,
    phal: expanded.phal,
    phalHi: expanded.phalHi,
    durationMin: expanded.durationMin,
    tags: ['panchatantra'],
    portrait: expanded.portrait,
  };
}
